# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'X' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for X

  pod 'Firebase/Core'
  pod 'Firebase/Database'

  target 'XTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'X-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for X-tvOS

  target 'X-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
